version: "3.1"
services:
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ./db_data/:/data/db/
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSSWORD}
